apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: devcluster
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/gke-cicd-428904/locations/us-central1/clusters/devcluster

