apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prodcluster
  annotations: {}
  labels: {}
description: prod
requireApproval: true
gke:
  cluster: projects/gke-cicd-428904/locations/us-central1/clusters/prodcluster

